# Generated by Django 5.0.3 on 2024-06-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
