# Generated by Django 5.0.3 on 2024-06-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogmodel_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='blog_content',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
