# Generated by Django 5.0.3 on 2024-06-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogmodel_blog_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='blog_content',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
